import 'package:flutter/material.dart';


class Intro
{
  static final List<Map<String,dynamic>>pic = [
    {'name':'WSB-119 FLUTTER','title':'Happy 78th Independence day','time':'15:14','raed':'9','pic':'assets/images/WSB.png','day':'Yesterday',},
    {'name':'Narendra Modi','title':'Hello Sir','time':'07:16','raed':'1','pic':'assets/images/Modi.png','day':'Yesterday'},
    {'name':'Mahendra Singh Dhoni','title':'Hello Sir','time':'19:14','raed':'6','pic':'assets/images/dhoni.png','day':'Yesterday',},
    {'name':'Ronaldo','title':'Hello Sir','time':'5:04','raed':'5','pic':'assets/images/Ronaldo.png','day':'Yesterday'},
    {'name':'Sachin Tendulkar','title':'Hello Sir','time':'12:16','raed':'3','pic':'assets/images/tendulkar.png','day':'Yesterday'},
    {'name':'Salman khan','title':'Hello Sir','time':'14:14','raed':'3','pic':'assets/images/Salman.png','day':'Yesterday'},
    {'name':'Sharukh Khan','title':'Hello Sir','time':'06:08','raed':'9','pic':'assets/images/Sharukh.png','day':'Yesterday'},
    {'name':'Ashokh Gehlot','title':'Hello Sir','time':'10:14','raed':'7','pic':'assets/images/Ashokh.png','day':'Yesterday'},
    {'name':'Sachin Pailot','title':'Hello Sir','time':'15:14','raed':'5','pic':'assets/images/pilot.png','day':'Yesterday'},
    {'name':'Rahul Gandhi','title':'Hello Sir','time':'03:59','raed':'4','pic':'assets/images/Rahul.png','day':'Yesterday'},
    {'name':'Amit Shah','title':'Hello Sir','time':'11:35','raed':'7','pic':'assets/images/Amit.png','day':'Yesterday'},
    {'name':'Yogi jii','title':'Hello Sir','time':'15:14','raed':'2','pic':'assets/images/Yogi.png','day':'Yesterday'},
    {'name':'Soniya Gandhi','title':'Hello Sir','time':'16:14','raed':'6','pic':'assets/images/Soniya.png','day':'Yesterday'},
    {'name':'Priyanka Gandhi','title':'Hello Sir','time':'09:14','raed':'5','pic':'assets/images/Priyanka gandhi.png','day':'Yesterday'},
    {'name':'Priyanka Chopra','title':'Hello Sir','time':'15:14','raed':'2','pic':'assets/images/Chopra.png','day':'Yesterday'},
    {'name':'Mukesh Ambani','title':'Hello Sir','time':'07:57','raed':'2','pic':'assets/images/Ambani.png','day':'Yesterday'},
    {'name':'Gautam Adani','title':'Hello Sir','time':'11:14','raed':'','pic':'assets/images/Adani.png','day':'Yesterday'},
    {'name':'Bill Gates','title':'Hello Sir','time':'23:29','raed':'5','pic':'assets/images/bill gates.png','day':'Yesterday'},
    {'name':'Mark Jukurbug','title':'Hello Sir','time':'22:39','raed':'3','pic':'assets/images/Zukarbug.png','day':'Yesterday'},
    {'name':'Jeff Bezos','title':'Hello Sir','time':'18:14','raed':'5','pic':'assets/images/Bezos.png','day':'Yesterday'},
    {'name':'My jio','title':'Hello Sir','time':'11:36','raed':'5','pic':'assets/images/Jio.png','day':'Yesterday'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png','day':'Yesterday'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},
    {'name':'Meta AI','title':'Hello Sir','time':'15:14','raed':'','pic':'assets/images/AI.png'},

  ];
}
